name: 'mancala'
version: 0.0.1
description: An implementation of mancala game using Dart Language.
#author: zidenis <denisalbuquerque@gmail.com>
#homepage: http://dart.blog.br

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'

transformers:
- dart_to_js_script_rewriter